### ISSUE TITLE
Why javax.ws.rs/javax.ws.rs-api/2.1.1 is build by JDK 9 ?

### ISSUE THREAD

**Issue by yuriy-slobodchikov** [eclipse-ee4j/jaxrs-api#754]
Manifest-Version: 1.0
Automatic-Module-Name: java.ws.rs
Bnd-LastModified: 1535126700945
Build-Id: 08/24/2018 12:04 PM
Build-Jdk: 9.0.1
...
Extension-Name: javax.ws.rs
Implementation-Version: 2.1.1

Looks like 2.1.1 was build with JDK 9 
It causes problems while loading in Java 8.

May be it should be rebuild by JDK 8 ?

**Comment by chkal** [comment]
AFAIK this is required for `module-info.java`.

> It causes problems while loading in Java 8.

Could you describe the problems you are running into in more detail?

**Comment by yuriy-slobodchikov** [comment]
Hello @chkal ,

In one project we use gradle jmeter plugin
It starts jmeter with our classes and all its dependencies
In one of our tests classes we use UriBuilder  from javax.ws.rs.core.UriBuilder with implementation
in org.glassfish.jersey.uri.internal.JerseyUriBuilder
and when we upgraded  javax.ws.rs to 2.1.1 we got error starting JMeter

2019/04/17 17:44:24 FATAL - jmeter.JMeter: An error occurred:  java.lang.UnsupportedClassVersionError: module-info has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.jorphan.reflect.ClassFinder.hasAnnotationOnMethod(ClassFinder.java:396)
	at org.apache.jorphan.reflect.ClassFinder.access$100(ClassFinder.java:47)
	at org.apache.jorphan.reflect.ClassFinder$AnnoClassFilter.accept(ClassFinder.java:117)
	at org.apache.jorphan.reflect.ClassFinder.findClassesInOnePath(ClassFinder.java:441)
	at org.apache.jorphan.reflect.ClassFinder.findClasses(ClassFinder.java:289)
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:264)
	at org.apache.jorphan.reflect.ClassFinder.findAnnotatedClasses(ClassFinder.java:211)
	at org.apache.jmeter.protocol.java.control.gui.JUnitTestSamplerGui.setupClasslist(JUnitTestSamplerGui.java:178)
	at org.apache.jmeter.protocol.java.control.gui.JUnitTestSamplerGui.itemStateChanged(JUnitTestSamplerGui.java:421)
	at javax.swing.AbstractButton.fireItemStateChanged(AbstractButton.java:2050)
	at javax.swing.AbstractButton$Handler.itemStateChanged(AbstractButton.java:2355)
	at javax.swing.DefaultButtonModel.fireItemStateChanged(DefaultButtonModel.java:455)
	at javax.swing.JToggleButton$ToggleButtonModel.setSelected(JToggleButton.java:272)
	at javax.swing.AbstractButton.setSelected(AbstractButton.java:348)
	at org.apache.jmeter.protocol.java.control.gui.JUnitTestSamplerGui.configure(JUnitTestSamplerGui.java:312)
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addComponent(JMeterTreeModel.java:146)
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addSubTree(JMeterTreeModel.java:121)
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addSubTree(JMeterTreeModel.java:121)
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addSubTree(JMeterTreeModel.java:121)
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addSubTree(JMeterTreeModel.java:121)
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addSubTree(JMeterTreeModel.java:113)
	at org.apache.jmeter.gui.GuiPackage.addSubTree(GuiPackage.java:492)
	at org.apache.jmeter.gui.action.Load.insertLoadedTree(Load.java:193)
	at org.apache.jmeter.gui.action.Load.insertLoadedTree(Load.java:229)
	at org.apache.jmeter.JMeter.startGui(JMeter.java:341)
	at org.apache.jmeter.JMeter.start(JMeter.java:480)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.jmeter.NewDriver.main(NewDriver.java:259)

**Comment by mkarg** [comment]
@yuriy-slobodchikov I cannot see any bug here. The file `module-info.class` *must* be compiled with Java 9 or later as it is part of JPMS; a Java 8 compiler cannot compile it. Do you really use the latest version of JMeter? It looks like it thinks that file is a class, which it actually isn't. Anyways, this isn't a JAX-RS issue, so while we can continue this discussion, I will close the issue as the question is answered.

**Comment by spericas** [comment]
@yuriy-slobodchikov At first glance, it seems that JMeter (or Jorphan) should be ignoring `module-info.class` during that scanning. Perhaps there's a newer version that does that?

**Comment by yuriy-slobodchikov** [comment]
@mkarg 
@spericas 

Thank you for responses so I got answer that compiling with JDK 9 was intentional.
I just downgraded back to 2.1 version in my project.
We did not upgrade JMeter to newest one because of other combinations of issues with libraries we use.

This ticket/question can be closed.
