### ISSUE TITLE
Throwing a `ForbiddenException` fails with ClassNotFound.

### ISSUE THREAD

**Issue by codeastra2** [eclipse-ee4j/jaxrs-api#882]
Env:
Java SDK version: 1.8
javax.ws.rs-api: 2.0
Using this a springboot server on centosVM. 
My maven dependency:
`
<dependency>
    <groupId>javax.ws.rs</groupId>
   <artifactId>javax.ws.rs-api</artifactId>
     <version>2.0</version>
   </dependency>
`

I needed to raise a `ForbiddenException` so i did a `throw new ForbiddenException("Evil Exception")`. However, on the receiver side instead of the said exception we got a different subclass of RunTime Exception:

`
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:152)
	at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:120)
	at javax.ws.rs.core.Response$ResponseBuilder.newInstance(Response.java:848)
	at javax.ws.rs.core.Response.status(Response.java:590)
	at javax.ws.rs.core.Response.status(Response.java:601)
	at javax.ws.rs.ClientErrorException.<init>(ClientErrorException.java:79)
	at javax.ws.rs.ForbiddenException.<init>(ForbiddenException.java:70)
	at com.nutanix.prism.notifications.core.TopicSubscriptionInterceptor.validateAuthorization(TopicSubscriptionInterceptor.java:112)
	at com.nutanix.prism.notifications.core.TopicSubscriptionInterceptor.preSend(TopicSubscriptionInterceptor.java:61)
	at org.springframework.messaging.support.AbstractMessageChannel$ChannelInterceptorChain.applyPreSend(AbstractMessageChannel.java:178)
	at org.springframework.messaging.support.AbstractMessageChannel.send(AbstractMessageChannel.java:132)
	... 33 more
Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at javax.ws.rs.ext.FactoryFinder.newInstance(FactoryFinder.java:114)
	at javax.ws.rs.ext.FactoryFinder.find(FactoryFinder.java:207)
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:135)
	... 43 more
`

**Comment by NicoNes** [comment]
Hi @codeastra2 ,

JAX-RS is just an API  and to make it work properly at runtime, you have to provide an implementation.

By default JAX-RS 2.0 looks for Jersey as default implementation but you can provide the implementation you want.

Hope this help,

Nicolas

**Comment by codeastra2** [comment]
What do you mean by implementation? All i am trying to do here is throwing an exception, should i do anything else to throw this exception ?

**Comment by spericas** [comment]
@codeastra2 What @NicoNes implies is that this is _not an issue in the Jakarta API_ (formerly JAX-RS). You need an implementation to use this API and the problem is likely in the integration; in this case you likely need to file this against SpringBoot or check their documentation. 

The error above seems to indicate that Jersey (java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl) is not on your classpath. But I don't know enough of Springboot to suggest a fix.
